"""empty message

Revision ID: 0b6eeb0d391a
Revises: 4664d30bc042
Create Date: 2021-12-02 19:36:37.291394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6eeb0d391a'
down_revision = '4664d30bc042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('test', type_='unique')
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_unique_constraint('test', ['test'])

    # ### end Alembic commands ###
