"""empty message

Revision ID: 26c1de74dc8e
Revises: f11b52642e3c
Create Date: 2022-01-10 18:11:31.844213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c1de74dc8e'
down_revision = 'f11b52642e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('departure_date',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('departure_time',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('departure_time',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('departure_date',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
