"""empty message

Revision ID: 59a8152a72cb
Revises: f75f2d10b85e
Create Date: 2022-01-10 18:17:29.870433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a8152a72cb'
down_revision = 'f75f2d10b85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_date', sa.String(length=35), nullable=True))
        batch_op.add_column(sa.Column('departure_time', sa.String(length=35), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_column('departure_time')
        batch_op.drop_column('departure_date')

    # ### end Alembic commands ###
