"""empty message

Revision ID: 9279fd146950
Revises: c29b5f311b75
Create Date: 2021-12-04 18:06:41.574135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9279fd146950'
down_revision = 'c29b5f311b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('departure_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('departure_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('departure_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('departure_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
