"""empty message

Revision ID: c29b5f311b75
Revises: a2b342b83ae0
Create Date: 2021-12-04 16:40:56.073378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29b5f311b75'
down_revision = 'a2b342b83ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.Integer(), nullable=True),
    sa.Column('point_departure', sa.String(length=50), nullable=False),
    sa.Column('point_destination', sa.String(length=50), nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('travel_time', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('Internal', 'International', name='routetype'), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    # ### end Alembic commands ###
