"""empty message

Revision ID: c84feb53739b
Revises: 12904314c630
Create Date: 2021-12-04 19:25:41.438315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84feb53739b'
down_revision = '12904314c630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('flight_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('departure_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('departure_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('travel_time',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('travel_time',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('departure_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('departure_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('flight_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
