"""empty message

Revision ID: d02b5e7854f3
Revises: c84feb53739b
Create Date: 2021-12-04 19:31:54.476696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02b5e7854f3'
down_revision = 'c84feb53739b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('flight_number', sa.INTEGER(), nullable=True),
    sa.Column('point_departure', sa.VARCHAR(length=50), nullable=False),
    sa.Column('point_destination', sa.VARCHAR(length=50), nullable=False),
    sa.Column('departure_date', sa.DATETIME(), nullable=True),
    sa.Column('departure_time', sa.DATETIME(), nullable=True),
    sa.Column('travel_time', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=13), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
