"""empty message

Revision ID: f75f2d10b85e
Revises: 944c02e11e5f
Create Date: 2022-01-10 18:17:17.343163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75f2d10b85e'
down_revision = '944c02e11e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_column('departure_time')
        batch_op.drop_column('departure_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_date', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('departure_time', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
